Met4FoF/agentMET4FOF

- AgentMET4FOF.py
That introduces the discussed format for the `pack_data` docstring. If you want to use it, just merge this *Pull Request* and transform the other docstrings to this format.
> Change docstring for pack_data

- develop/develop_zema_agents.py
- develop/main_zema_agents.py
Added regression_agent to the develop_zema_agents.py with all required imports, and added few lines to the main_zema_agents.py to enable the usage of the regression_agent.
> Added regression_agent..

- .circleci/config.yml
- .coveragerc
- .gitignore
- README.md
- develop/develop_zema_datastream.py
- docs/.readthedocs.yml
- docs/Getting started.rst
- docs/conf.py
- docs/index.rst
- environment.yml
- requirements.txt
This inserts the updated *requirements.txt* in the builds of *Read the Docs* to allow a succesful build again. Then we inserted more draft content to prepare better documentation. The content needs to be added especially in the [`Getting started.rst`](https://github.com/bangxiangyong/agentMet4FoF/blob/repair_readthedocs/docs/Getting%20started.rst) and the [`index.rst`](https://github.com/bangxiangyong/agentMet4FoF/blob/repair_readthedocs/docs/index.rst).
> Repair ReadTheDocs

- .circleci/config.yml
- .coveragerc
- .gitignore
- README.md
- develop/develop_zema_datastream.py
- requirements.txt
In the first step we add the necessary dependencies to *requirements.txt*:
*   dash
*   dash-cytoscape
*   networkx
*   multiprocess
*   h5py
*   requests
Afterwards we fixed CI config and coverage report to new project structure. Finally we uploaded the first coverage report and inserted all three available badges into README.md:
*   CircleCI
*   ReadTheDocs
*   CodeCov.
> This adds what is needed to successfully run the tests  on CircleCI

- docs/conf.py
- docs/sphinx-requirements.txt
> Introduce ability to write markdown docs

- .gitignore
This is meant to resolve #66 .
> Remove .gitignore to the essentials

- agentMET4FOF/agents.py
- agentMET4FOF/dashboard/Dashboard.py
- agentMET4FOF/dashboard/Dashboard_Control.py
- agentMET4FOF/dashboard/Dashboard_agt_net.py
- agentMET4FOF/dashboard/Dashboard_ml_exp.py
- agentMET4FOF/develop/buffer_deque.py
- agentMET4FOF/develop/datastream.py
- agentMET4FOF/develop/evaluator.py
This will resolve #79 . We just test the submodules now with this commit and if everything works fine, we can review and merge this.
> Refactor all internal absolute imports in the agents core

- .circleci/config.yml
We introduce a job in our CI pipeline taking care of testing the _setup.py_. The package gets installed based on the _setup.py_ configuration and tested against the full suite.
> Improve testing the installation

- .circleci/config.yml
- agentMET4FOF/dashboard/Dashboard_agt_net.py
- dev-requirements.txt
- setup.py
- tests/test_dashboard.py
Since in [one of the use cases](https://github.com/PTB-PSt1/agentMET4FOF/commit/680bd5365eca07152daec9f1db6c1733857c1dae) we needed the ability to send several plots at a time, we introduced this change and now want to publish it as a feature. This  should cover the actual feature, some testing and of course appropriate documentation.
Resolves #87, resolves #90 and resolves #91 .
We still need to separately resolve issue #93, the related issue about the feature's documentation.
PS: This takes the place of previously opened #92, which diverged to far from the base branch to keep track of the actual changes.
> Refine dashboard for iterables of plots

- agentMET4FOF/agents.py
- agentMET4FOF/dashboard/Dashboard_agt_net.py
- agentMET4FOF/dashboard/LayoutHelper.py
- agentMET4FOF/dashboard/assets/render_mpld3.js
- agentMET4FOF/streams.py
- agentMET4FOF_tutorials/buffering/basic_buffering.py
- agentMET4FOF_tutorials/buffering/moving_average.py
- agentMET4FOF_tutorials/datastreams/multi_generator.py
- agentMET4FOF_tutorials/datastreams/simple_generator.py
- agentMET4FOF_tutorials/plotting/basic_memory_plot.py
- agentMET4FOF_tutorials/plotting/basic_send_plot.py
- agentMET4FOF_tutorials/plotting/custom_memory_plot.py
- agentMET4FOF_tutorials/plotting/list_of_plots.py
- agentMET4FOF_tutorials/tutorial_2_math_agent.py
- agentMET4FOF_tutorials/tutorial_3_multi_channel.py
- agentMET4FOF_tutorials/tutorial_5_coalition.py
I will add documentation for various issues raised:
buffer_filled : https://github.com/bangxiangyong/agentMET4FOF/issues/89
> Add documentation for various issues

- agentMET4FOF/streams.py
- docs/agentMET4FOF_dashboard.rst
This introduces very minor changes, which allow for a successful build of the docs again.
> Repair some minor issues that prevent the creation of the docs

- .circleci/config.yml
- agentMET4FOF/agents.py
- agentMET4FOF/dashboard/Dashboard.py
- agentMET4FOF/dashboard/Dashboard_agt_net.py
- agentMET4FOF/metrological_streams.py
- agentMET4FOF/streams.py
- agentMET4FOF_tutorials/datastreams/gaussianshock_generator.py
- agentMET4FOF_tutorials/tutorial_2_math_agent.py
- agentMET4FOF_tutorials/tutorial_6_mesa_backend.py
- setup.py
- tests/conftest.py
- tests/test_network.py
- tests/test_tutorials.py
Please check, if this is what you inteded. To me it looks, as if the changes merged in fine. I would invest some time tomorrow to get rid of everything that dealt with `multiprocess.Process` and thus simplify `AgentDashboard` again and its usage in _Dashboard_agt_net_.
> Merged branch develop after all those PRs into Enhance_UI

- agentMET4FOF/dashboard/Dashboard.py
- agentMET4FOF/dashboard/Dashboard_agt_net.py
- requirements.txt
- setup.py
Quite urgent fixes i'd say on two minor things: 
1) using Process for Dashboard on osbrain backend
2) dashboard monitor agent key issue
> Fix multiprocess and bugs

- agentMET4FOF/metrological_streams.py
Just some ideas... what do you think?
> Refactor default uncertainty behaviour into MetrologicalDataStreamMet4FoF

- README.md
Would "facilitating" or "expediting" work instead?
> changed "impacting on" to "enabling"

- .circleci/config.yml
- README.md
- dev-requirements.txt
- environment.yml
- requirements.txt
Codecov had [some issues](https://about.codecov.io/security-update/). We updated our GitHub access token and exchanged the mechanism for CircleCI to make use of it to further strengthen security.
Additionally we intend to update the current requirements to avoid any security issues with outdated packages.
Apparently there is something wrong with the Miniconda environment setup. We will check back on this tomorrow. More on the installation of Miniconda in the [official docs](https://conda.io/projects/conda/en/latest/user-guide/install/macos.html#install-macos-silent).
> Introduce new context after Codecov breach and possible credential leak

- docs/conf.py
After removing the old changelog we forgot to replace its usage by the new changelog
> Repair sphinx docs

- tests/conftest.py
Set test_timeout = 20 instead of 10.
> Update conftest.py (test_timeout)

- setup.cfg
This should resolve #233 by adapting the according setting.
> Include refactor commit type in changelog

- agentMET4FOF/agents/metrological_base_agents.py
> Remove self.memory from MetrologicalMonitorAgent

- .gitignore
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- docs/INSTALL.md
- docs/conf.py
… and some other long-needed documentation.
Resolves #253 .
> Finally add a code of conduct

- setup.py
Clean unneeded Command and introduce version specific URLs.
> Update content of setup.py
