Met4FoF/agentMET4FOF

docs/conf.py
This adds Haris Lulic from IMBIH to the authors in the Sphinx output on [Read the Docs](https://agentmet4fof.readthedocs.io/en/include_haris_as_author/#references).
=> Add Haris as author in docs

docs/agentMET4FOF agents.rst, docs/agentMET4FOF streams.rst
This inserts the proper package name into the docs for repairing the automodule entries in [agentMET4FOF agents.rst](https://github.com/bangxiangyong/agentMET4FOF/blob/master/docs/agentMET4FOF%20agents.rst#agentmet4fof-agents) and [agentMET4FOF streams.rst](https://github.com/bangxiangyong/agentMET4FOF/blob/master/docs/agentMET4FOF%20streams.rst#agentmet4fof-streams).
=> Resolve #14 by repairing automodules in *agents.rst and *streams.rst

license.md
This adds the LGPL license used for the Met4FoF Code to the repository. Feel free to choose another license according to IfM's needs, but you should add one.
=> Insert license

README.md, agentMET4FOF/dashboard/Dashboard_Control.py, agentMET4FOF_tutorials/tutorial_1_generator_agent.py, environment.yml, setup.py
Several issues just recently occured, which we solve in this PR:
- we used type annotations which are not compatible with Python 3.5 anymore, so we require Python 3.6 in the _README.md_, the _environment.yml_ and the _setup.py_
- introduce a `__init__.py` in the package `develop`
- fix two import statements in _Dashboard_Control.py_ which did not work with Python 3.6
- Correct a comment about a type hint in *tutorial_1_generator_agent.py*
- Correct the call for the tutorial in the README.md
=> Fix issues with the PyPI package and other minors

agentMET4FOF/agents.py, agentMET4FOF/dashboard/Dashboard_agt_net.py, tests/test_send_plot.py, tests/test_send_plot_image.py, tests/test_send_plot_plotly.py
By specifying the `mode` keyword in the agent's send_plot(fig,mode) function, we can select the mechanism of which matplotlib figures can converted and sent to the MonitorAgent to be rendered on the web visualisation. 
if mode == 
1. "image": convert to image
2. "plotly": convert to plotly figure
also modifed the test file to test for both modes of conversion. This should resolve #53 .
=> Select different conversion modes of send_plot for matplotlib figures

agentMET4FOF/agents.py, docs/sphinx-requirements.txt, requirements.txt, setup.py
Here we are investigating the issue #58 . If this is successful we either know why we use the fork [`multiprocess`](https://pypi.org/project/multiprocess/) over built-in [`multiprocessing`](https://docs.python.org/3/library/multiprocessing.html) and have a test, ensuring that everything works as expected with `multiprocess` and fails by mocking `multiprocessing`, so we notice the moment when we could switch to the preferable built-in library. Otherwise we should switch right away and will do this here to resolve #58 .
=> Exchange multiprocess by official multiprocessing

agentMET4FOF/agents.py
We actually do not know, if this is the cause, but the strange and unneeded import statement
`from .dashboard.Dashboard import AgentDashboard as AgentDashboard`
should be removed to be concise.
=> Fix unusual import in  agents.py maybe causing problems

agentMET4FOF/agents.py
We merge the child process' clutter right after ending the dashboard itself.
=> Shutdown dashboard more cleanly

agentMET4FOF/agents.py, agentMET4FOF/dashboard/Dashboard_agt_net.py, agentMET4FOF/dashboard/assets/render_mpld3.js, agentMET4FOF_tutorials/plotting/basic_memory_plot.py, agentMET4FOF_tutorials/plotting/basic_send_plot.py, agentMET4FOF_tutorials/plotting/custom_memory_plot.py, agentMET4FOF_tutorials/plotting/list_of_plots.py
Now we can do : agent.send_plot(matplotlib.Figure, mode="mpld3")
This is a working edition , compared to the previous pull request  (https://github.com/bangxiangyong/agentMET4FOF/pull/56) which was left as a draft pull and its code base version was too far behind.
=> Introduce mpld3 as a mode of rendering matplotlib figures

docs/conf.py
This should resolve #123 .
Checkout the ["new" docs](https://agentmet4fof.readthedocs.io/en/improve_docs/agentMET4FOF_tutorials/tutorial_1_generator_agent.html) with the little :heavy_plus_sign: next to the heading in the sidebar.
=> Introduce more levels in documentation menus on ReadTheDocs

tests/conftest.py
Our test were failing sometimes. We needed to raise the timeout for our tests to allow for proper shutdown of our networks.
=> Raise timeout in pytest's conftest.py

agentMET4FOF_tutorials/tutorial_4_metrological_streams.py
This keeps the amount of datapoints being shown in the plot on less or equal 50. That greatly improves readability after some few seconds of execution time. What do you think?
=> Improve readability of tutorial 4's plot

agentMET4FOF/agents.py, agentMET4FOF/dashboard/Dashboard.py, agentMET4FOF/dashboard/Dashboard_agt_net.py, agentMET4FOF_tutorials/tutorial_6_mesa_backend.py, tests/test_network.py, tests/test_tutorials.py
This is based on the assumption we will at some point merge the transfer of tutorial agents into develop. If we do not merge it, then we just build upon any other existing tutorial for the mesa backend.
This resolves #167
=> Introduce tutorial 6 for using the Mesa backend

.circleci/config.yml, .coveragerc, dev-requirements.in, dev-requirements.txt, requirements.txt, setup.py, tox.ini
Release 0.5.0 unfortunately does not contain one of the introduced dependencies in the _setup.py_ and thus not the _requirements.txt_ but only in the _dev-requirements_, which was sufficient until 0.4.1 but not anymore. We introduce the needed `psutil` as a bugfix.
=> Introduce psutil into dependencies and recompile dependencies

agentMET4FOF/metrological_streams.py, agentMET4FOF/streams.py, agentMET4FOF_tutorials/tutorial_4_metrological_streams.py
next_sample_generator in metrological_streams was previously only able to return batches of size 1. The default generators were rewritten such that batches of a given size can be returned.
=> next sample generator for batch size > 1

.circleci/config.yml, dev-requirements.in, dev-requirements.txt, docs/CONTRIBUTING.md, docs/conf.py, requirements.txt, setup.cfg
This is to half-automate the release process and introduce the creation and maintain a `docs/CHANGELOG.md` to prepare for automatic release creation.
We resolve #52 with this.
=> Introduce python-semantic-release

agentMET4FOF/agents.py, agentMET4FOF/dashboard/Dashboard_agt_net.py, agentMET4FOF/dashboard/LayoutHelper.py, tests/test_metadata_metrological_agent.py
We spotted a left over from the times of `self.memory` in _agents.py_ and went to correct that. Then we stumbled across some minor issues in old docstrings and a loop over a dictionary via the key, where we could simply loop over keys and values. Hope this breaks nothing.
=> Fix residing agent memory

agentMET4FOF_tutorials/buffering/moving_average.py
- I must have missed out this commit which i was supposed to make earlier, importantly, this aligns with the video tutorial content
- of course, more elegantly could use the metrological sine stream with noise which was introduced in this branch.
- Edit: found the commit here : https://github.com/Met4FoF/agentMET4FOF/commit/25277de757d72105d5ab1b24bc0f1d913a0dca72 which was not merged yet in another branch..
=> introduce noise to the tutorial of buffering moving average

agentMET4FOF/metrological_streams.py
`np.arange(self._sample_idx, self._sample_idx + batch_size, 1.0).reshape(-1, 1) / self.sfreq` is fine. 
`np.arange(self._sample_idx, self._sample_idx + batch_size, 1.0 / self.sfreq).reshape(-1, 1) ` was returning time arrays of the wrong size and generating strange plots.
=> fixed error in _time array. wrong values were being returned

.gitignore, CHANGELOG, docs/conf.py, docs/index.rst
That is obviously pretty minor, but now that we have the CHANGELOG I thought, we might as well show it. :smile: 
Check out the [new docs](https://agentmet4fof.readthedocs.io/en/add_changeog_to_docs/)!
=> Include CHANGELOG into docs

agentMET4FOF/agents.py, agentMET4FOF/dashboard/Dashboard.py
We accidentally intialized the private variables `_controller` and `_logger` without the underscores in _agents.py_. In consequence we had to check later during runtime, if these variables had already been initialized and otherwise set the appropriate values. We corrected now the initialization and removed the checks, because they should be no longer needed.
This should resolve #168 .
=> Refactor controller and logger in agents.py to _controller and _logger

agentMET4FOF/dashboard/Dashboard.py
... and not only dashboard, but the WSGI server in the background as well,which was previously left waiting for incoming connections for about a minute.
@bangxiangyong Please check, if this version runs and stops as expected as well from your console and can be restarted without any problems.
If your tests are succesfull, this should finally resolve #186 .
=> Finally resolve #186 by cleanly shutting down dashboard

agentMET4FOF/dashboard/Dashboard.py, dev-requirements.txt, requirements.txt, setup.py
We have introduced a dependency `pathos` but only  use their class Process, which in turn looks, as if it is simply the `multiprocess.context.Process` class, they themselves import from another third-party library `multiprocess`. It should suffice to directly use the `multiprocess.context.Process`.
Notice my [comment on my thoughts in the corresponding issue](https://github.com/Met4FoF/agentMET4FOF/issues/189#issuecomment-800204272) and especially the difference between in-built _multiprocess**ing**_ and the fork _multiprocess_ from the _pathos_ guys. 
@bangxiangyong Please check if everything for which you introduced the `pathos` import in _agentMET4FOF.dashboard.Dashboard_ still works.
This is meant to resolve #189 .
=> Replace pathos by multiprocess

.circleci/config.yml, README.md, agentMET4FOF/metrological_agents.py, agentMET4FOF/metrological_streams.py, dev-requirements.txt, environment.yml, requirements.txt
A default generator agent has been added to metrological_agents.py. When no signal is specified, the MetrologicalSineGenerator is chosen as the input signal.
=> Default metrological generator agents

agentMET4FOF/metrological_agents.py
Please compare the [old version](https://agentmet4fof.readthedocs.io/en/default_metrological_generator_agents/agentMET4FOF_metrological_agents.html) against the [new version](https://agentmet4fof.readthedocs.io/en/improve_docstrings_of_input_data_and_output_data/agentMET4FOF_metrological_agents.html).
=> Reformat two of our docstrings to properly display those example values in the docs

agentMET4FOF/metrological_agents.py, agentMET4FOF/metrological_streams.py
When agentMET4FOF is used as a submodule in other packages, it is necessary to have relative imports in the core modules, as we noticed earlier (#79). This PR realizes this principle for the metrolgical modules.
=> Refactor metrological agents and streams to make imports relative

agentMET4FOF/dashboard/Dashboard.py
This should enable docker deployment without interfering with anything else up until now and thus resolves #254 . It is a huge step towards #215 .
=> Change delivery ip to 0.0.0.0, i.e. all interfaces instead of 127.0.0.1 to enable docker deployment

agentMET4FOF/dashboard/Dashboard_agt_net.py
Previously the agents to plot from their buffer were chosen depending on their names containing the substring `Monitor`. We changed this, so that now all agents of types `MetrologicalMonitorAgent` and `MonitorAgent` are considered. This needed a new method to return agents of a specific type from the network.
Additionally we allow spaces in agents' names, which allows to generate nicer plots.
=> Repair monitor agent logic

agentMET4FOF/dashboard/Dashboard_agt_net.py
… because this is what happens.
=> Rename dashboard button to create downloadable image of agent network to "Export png"

agentMET4FOF/agents/base_agents.py
This resolves #307 . Maybe we should take the opportunity to fix the logic of the class in terms of moving the initialization of instance parameters into the `__init__` method?!
=> Fix misleading comment in docstring of init_agent

.circleci/config.yml, CONTRIBUTING.md, README.md
... is it adds another layer of complexity to the pipeline and it is not really needed as of now. Noone noticed for three years that the coverage was not updated due to an unnoticed error in the mechanism.
=> Remove CodeCov
